id: P006951
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG18170
  title: དྭགས་པོ་ཆོས་བཞིའི་རྩ་འགྲེལ།
  author: ''
  volumes:
    76783fe1d48d4512a99e5428aa8a4d75:
      image_group_id: I1KG18212
      title: Volume 1 of dwags po chos bzhi'i rtsa 'grel/
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
