id: P006951
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18170
  title: དྭགས་པོ་ཆོས་བཞིའི་རྩ་འགྲེལ།
  author: ''
  volumes:
    d9f9e18457d64b06be178dfdd63ec3e4:
      image_group_id: I1KG18212
      title: ''
      volume_number: 1
      total_pages: 294
ebook_metadata:
  title: དྭགས་པོ་ཆོས་བཞིའི་རྩ་འགྲེལ།
  author: ''
  sku: P006951
  cover: cover.jpg
  layers:
  - pagination
